{{- define "helmet.app" -}}

{{- if .Values.authPolicy.enabled }}
{{ include "helmet.authpolicy" . }}
{{- end }}

# Istio virtual service.
{{- if .Values.virtualService.enabled -}}
{{ include "helmet.virtualservice" . }}
{{- end }}

# Cleanup storage
{{- if .Values.cleanup.enabled }}
{{ include "helmet.cleanup" . }}
{{- end }}

{{- if .Values.persistence.enabled }}
{{ include "helmet.storage" . }}
{{- end }}


{{ include "helmet.serviceaccount" . }}
{{ include "helmet.servicemonitor" . }}
{{ include "helmet.podmonitor" . }}
{{- end }}
