{{- define "helmet.deployment" -}}
{{- if .Values.deployment.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    {{- if .Values.deployment.annotations }}
    {{- toYaml .Values.deployment.annotations | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.deployment.replicaCount | default 1 }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        {{- if .Values.deployment.podLabels }}
        {{- toYaml .Values.deployment.podLabels | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.deployment.podAnnotations }}
        {{- toYaml .Values.deployment.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- range $key, $value := .Values.deployment.nodeSelector }}
        {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      {{- if .Values.deployment.tolerations }}
      tolerations: {{- toYaml .Values.deployment.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.affinity }}
      affinity: {{- toYaml .Values.deployment.affinity | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy | default "IfNotPresent" }}
          {{- if .Values.deployment.securityContext }}
          securityContext: {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.command }}
          command: {{- toYaml .Values.deployment.command | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.args }}
          args: {{- toYaml .Values.deployment.args | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.env }}
          env:
            {{- range $key, $value := .Values.deployment.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.deployment.envFrom }}
          envFrom: {{- toYaml .Values.deployment.envFrom | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.ports }}
          ports: {{- toYaml .Values.deployment.ports | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.resources }}
          resources: {{- toYaml .Values.deployment.resources | nindent 12 }}
          {{- end }}
          {{- if or .Values.deployment.livenessProbe .Values.deployment.readinessProbe }}
          {{- if .Values.deployment.livenessProbe }}
          livenessProbe: {{- toYaml .Values.deployment.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.readinessProbe }}
          readinessProbe: {{- toYaml .Values.deployment.readinessProbe | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.deployment.volumeMounts }}
          volumeMounts: {{- toYaml .Values.deployment.volumeMounts | nindent 12 }}
          {{- end }}
      {{- if .Values.deployment.volumes }}
      volumes: {{- toYaml .Values.deployment.volumes | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.imagePullSecrets }}
      imagePullSecrets: {{- toYaml .Values.deployment.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helmet.serviceAccountName" . }}
{{- end }}
{{- end }}