{{- define "helmet.virtualservice" -}}
{{- if .Values.virtualService.enabled }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "common.names.fullname" . }}-virtualservice
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  hosts:
    {{- toYaml .Values.virtualService.hosts | nindent 2 }}
  {{- if .Values.virtualService.gateways }}
  gateways:
    {{- toYaml .Values.virtualService.gateways | nindent 2 }}
  {{- end }}
  {{- if .Values.virtualService.http }}
  http:
    {{- toYaml .Values.virtualService.http | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}